services:
  egoblur-vrs-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: ziruiw/egoblur-vrs-gpu:1.0
    container_name: egoblur_vrs_gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - TORCH_CUDA_ARCH_LIST=6.0;6.1;7.0;7.5;8.0;8.6;8.9
    stdin_open: true
    tty: true
